// src\app\layout.js

import PropTypes from "prop-types";
import "./styles/globals.css";

export const metadata = {
  title: "OTT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body
        style={{ fontFamily: '"Gabarito", sans-serif' }}
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
